config/routes.rb
Rails.application.routes.draw do

  get 'braintree/new'
  resources :documents
  resources :users

  resources :sessions

  root "welcome#index", as: "home"

  post 'braintree/checkout'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/document.rb
class Document < ApplicationRecord
	

	validates :deadline, presence: true

	validates :file_name, presence: true

	
end 

app/models/user.rb
class User < ApplicationRecord
	has_secure_password
	enum role:[:user, :superadmin]
	validates :email, uniqueness: true, presence: true

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
	protect_from_forgery

	private

	def current_user
		@current_user ||= User.find(session[:user_id]) if session[:user_id]

	end

	helper_method :current_user

	def authorise
		redirect_to new_session_path, alert: 'Not authorised' if current_user.nil? 
	end

	def superadmin
		redirect_to home_path, alert: 'You\'re not the superadmin. What are you trying to do.' if User.find(session[:user_id]).role != 'superadmin'
	end

end

app/controllers/braintree_controller.rb
class BraintreeController < ApplicationController
  def new

  	@client_token = Braintree::ClientToken.generate

  end

  def checkout
  nonce_from_the_client = params[:checkout_form][:payment_method_nonce]

  result = Braintree::Transaction.sale(
   :amount => params[:checkout_form][:amount], #this is currently hardcoded
   :payment_method_nonce => nonce_from_the_client,
   :options => {
      :submit_for_settlement => true
    }
   )

	  if result.success?
	    redirect_back fallback_location: new_user_path , :flash => { :success => "Transaction successful!" }
	  else
	    redirect_back fallback_location: new_user_path, :flash => { :error => "Transaction failed. Please try again." }
	  end
	end

end

app/controllers/documents_controller.rb
class DocumentsController < ApplicationController
	before_action :authorise, :only => [:new, :create, :show, :index]

	def new
		@document = Document.new
	end

	def create
		
		@document = Document.new(allowed_params)

		@superadmin = User.find_by(email: 'choohor@gmail.com')
		@reminder_date = @document.reminder_date
		@period = (@document.deadline - @reminder_date).to_i
		@time_till_email = (@reminder_date - Date.today).to_i
		if @document.save
			ReminderEmailJob.set(wait: @time_till_email.days).perform_later(@superadmin, @document)
			redirect_to document_path(@document.id), notice: "Your entry has been committed and a reminder email will be sent #{@period} days before the deadline."
		else
			render :new
		end
	end

	def show
		@document = Document.find(params[:id])
	end

	def index

		@search = Document.ransack(params[:q]) 
		@result = @search.result

		@documents = Document.order(:file_name)

		@documents_deadline = Document.order(:deadline)

		@documents_created = Document.order(:created_at)
	end

	def destroy
		@document = Document.find(params[:id])
		@document.destroy
		redirect_to documents_path
	end


	private

	def allowed_params
		params.require(:document).permit(:file_name, :client, :deadline, :reminder_date)
	end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
  	user = User.find_by(email: params[:email])

  	if user && user.authenticate(params[:password]) && user.verified == true
  		session[:user_id] = user.id
  		redirect_to home_path, notice: "Logged in!"
		else
			render "new"
			
			if user.verified == false
				flash.alert = "Please wait to be verified by an admin"
			else 
				flash.alert = "Your email or password is invalid"
			end
							
		end
	end

	def destroy
		session[:user_id] = nil
		redirect_to home_path, notice: 'Logged out.'
	end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
	before_action :authorise, :only => [:index]
	before_action :superadmin, :only => [:index]


	def new
		@user = User.new
	end

	def create
		
		@user = User.new(allowed_params)
		if @user.save
			redirect_to home_path, notice: 'Thanks for signing up, please wait to be verified before you can use this site'
		else
			render :new
		end
	end

	def index

		@users = User.where(verified: false).order(:last_name)
	end

	def update
		@user = User.find(params[:id]).update(verified: true)

		redirect_back fallback_location: users_path
	end

	private

	def allowed_params
		params.require(:user).permit(:first_name, :last_name, :title, :email, :password, :password_confirmation)
	end

end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
	#before_filter :authorise, only [:edit, :index]
	def index 

	end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/braintree_helper.rb
module BraintreeHelper
end

app/helpers/documents_helper.rb
module DocumentsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/braintree/new.html.erb
<div class="demo-frame">

  <%= form_for :checkout_form, url: braintree_checkout_path, html: { id: "cardForm"} do |form| %>

  	<%= form.number_field :amount , placeholder: 'Amount To Be Paid' %><br/><br/>

    <%= form.label :card_number, "Credit Card Number", html: {class: "hosted-fields--label"} %>
    <div id="card-number" class="hosted-field"></div>

    <%= form.label :expiration_date, "Expiration Date", html: {class: "hosted-fields--label"} %>
    <div id="expiration-date" class="hosted-field"></div>

    <%= form.label :cvv, "CVV", html: {class: "hosted-fields--label"} %>
    <div id="cvv" class="hosted-field"></div>


    <%= form.hidden_field "payment_method_nonce" %>

    <div class="button-container">
      <%= form.submit "Purchase", disabled: true, class: "btn btn-primary", id: "submit-payment-btn" %>
    </div>
  <% end %>
  
</div>


<!-- Load the Client component. -->
<script src="https://js.braintreegateway.com/web/3.6.3/js/client.min.js"></script>

<!-- Load the Hosted Fields component. -->
<script src="https://js.braintreegateway.com/web/3.6.3/js/hosted-fields.min.js"></script>


<script>

var form = document.querySelector('#cardForm');
var submit = document.querySelector("#submit-payment-btn");
var authorization = '<%= @client_token %>';

braintree.client.create({
  // Replace this with your own authorization.
  authorization: authorization
}, function (clientErr, clientInstance) {
  if (clientErr) {
    // Handle error in client creation
    return;
  }

  braintree.hostedFields.create({
    client: clientInstance,
    styles: {
      'input': {
        'font-size': '14pt'
      },
      'input.invalid': {
        'color': 'red'
      },
      'input.valid': {
        'color': 'green'
      }
    },
    fields: {
      number: {
        selector: '#card-number',
        placeholder: '4111 1111 1111 1111'
      },
      cvv: {
        selector: '#cvv',
        placeholder: '123'
      },
      expirationDate: {
        selector: '#expiration-date',
        placeholder: '10/2019'
      }
    }
  }, function (hostedFieldsErr, hostedFieldsInstance) {
    if (hostedFieldsErr) {
      // Handle error in Hosted Fields creation
      return;
    }

    submit.removeAttribute('disabled');

    form.addEventListener('submit', function (event) {
      event.preventDefault();

      hostedFieldsInstance.tokenize(function (tokenizeErr, payload) {
        if (tokenizeErr) {
          // Handle error in Hosted Fields tokenization
          return;
        }

        // Put `payload.nonce` into the `payment_method_nonce` input, and then
        // submit the form. Alternatively, you could send the nonce to your server
        // with AJAX.
        document.querySelector('input[name="checkout_form[payment_method_nonce]"]').value = payload.nonce;
        form.submit();
      });
    }, false);
  });
});
</script>

app/views/documents/index.html.erb
<h2> All Documents Within The Database </h2>
<br/><br/>


<!--Search function -->
<%= search_form_for @search do |f| %>

	<%= f.label :file_name_or_client_name_cont %>
	<%= f.search_field :file_name_or_client_cont %> 
	<%= f.submit %>

<% end %>
<%if !@result.empty? %>
	<h2> Search Results </h2>
	<div>
		<% @result.each do |result| %>
			<h3><a href="/documents/<%=result.id%>"><%= result.file_name %> </a></h3>
			<p>Client: <%= result.client %></p>
			<p> Deadline <em>(year/ month, day)</em>: <%= result.deadline %></p>
			<br/><hr/>
		<% end %>
	</div>
<% else %>
<h3> Your search didn't return any results. </h3>
<%end %>

<br/><br/>


<div> Sort <div class = "A"><a href="#">Alphabetically</a></div> <div class = "B"><a href= "#">By Deadline</a></div> <div class = "C"><a href = "#">Entry Date</a></div></div>



<div id = "alphabetical">
	<p> <em>Sorted alphabetically </em></p>

	<div>
	<% @documents.each do |doc| %>
		
		<h3><a href = "/documents/<%= doc.id%>"> <%= doc.file_name %> </a></h3>

		<p> Client: <%= doc.client %> </p>
		<p> Deadline <em> (year, month, day)</em>: <%= doc.deadline %> </p>

		<%= form_tag("/documents/#{doc.id}", method: :delete) do %>
	    			<input type="submit" value="Delete Entry" />
		<% end %>   

		<br/><br/><hr/>

	<% end %>
	</div>
</div>
<hr/>


<div style = "display: none">
	<div id = "deadline">
	<p><em>Sorted by nearest approaching deadline </em></p>

	<div>
		<% @documents_deadline.each do |doc| %>
			<h3><a href = "/documents/<%= doc.id%>"> <%= doc.file_name %> </a></h3>

			<p> Client: <%= doc.client %> </p>
			<p> Deadline <em> (year, month, day)</em>: <%= doc.deadline %> </p>
			<%= form_tag("/documents/#{doc.id}", method: :delete) do %>
	    	<input type="submit" value="Delete Entry" />
			<% end %> 
			<br/><br/><hr/>

		<% end %>

	</div>
	</div>
</div>
<hr/>


<div style = "display: none">
	<div id = "created">
	<p><em>Sorted by oldest entries </em></p>

	<div>
		<% @documents_created.each do |doc| %>
			<h3><a href = "/documents/<%= doc.id%>"> <%= doc.file_name %> </a></h3>

			<p> Client: <%= doc.client %> </p>
			<p> Deadline <em> (year, month, day)</em>: <%= doc.deadline %> </p>
			<%= form_tag("/documents/#{doc.id}", method: :delete) do %>
	    	<input type="submit" value="Delete Entry" />
			<% end %> 
			<br/><br/><hr/>

		<% end %>

	</div>
	</div>	
</div>
<hr/>

<script>


	$(".A").click(function(event) {
		event.preventDefault();
		$("#alphabetical").load("/documents #alphabetical");
	});

	$(".B").click(function(event) {
		event.preventDefault();
		$("#alphabetical").load("/documents #deadline");
	});

	$(".C").click(function() {
		event.preventDefault();
		$("#alphabetical").load("/documents #created");
	});


	function addClass()
	


</script>

app/views/documents/new.html.erb
<h1> New Entry of File/Document </h1>

<%= form_for @document do |f| %>
	<% if @document.errors.any? %>
		<div class= "errors">
			<h3>Form is invalid</h3>
			<ul>
				<% @document.errors.full_messages.each do |m| %>
					<li> <%= m %> </li>
				<% end %>
			</ul>
		</div>
	<% end %>

	<div class="field">
		<%= f.label :"File Name" %><br/>
		<%= f.text_field :file_name %>
	</div>

	<div class="field">
		<%= f.label :Client %><br/>
		<%= f.text_field :client %>
	</div>

	<div class="field">
		<%= f.label :Deadline %><br/>
		<%= f.date_field :deadline %>

	</div>
	<br/>

	<div class="field">
		<%= f.label :"Set Date For A Reminder Email To Be Sent" %><br/>
		<%= f.date_field :reminder_date %>

	</div>

	
	<div class="submit">
		<%= f.submit "Submit Entry" %></div>

<% end %>

app/views/documents/show.html.erb
<h2> <%= @document.file_name %> </h2>

<br>

<h4> Client: <%= @document.client%></h4>

<br/>

<h2> Deadline <em> (year, month, day)</em>: <%= @document.deadline %> </h2>

<%= form_tag("/documents/#{params[:id]}", method: :delete) do %>
	    			<input type="submit" value="Delete Entry" />
		<% end %>   

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Filing</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.2/css/bootstrap.min.css" integrity="sha384-Smlep5jCw/wG7hdkwQ/Z5nLIefveQRIY9nfy6xoR1uRYBtpZgI6339F5dgvm/e9B" crossorigin="anonymous">

    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js" integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.2/js/bootstrap.min.js" integrity="sha384-o+RDsa0aLu++PJvFqy8fFScvbHFLtbvScb8AjopnFD+iEQ7wo/CG0xlczd+2O/em" crossorigin="anonymous"></script>
    
    <script src="https://code.jquery.com/jquery-3.3.1.min.js" integrity="sha256-FgpCb/KJQlLNfOu91ta32o/NMZxltwRo8QtmkMRdAu8=" crossorigin="anonymous"></script>

  </head>

  <body>

    <p><a href = "/"> Home </a></p>
    <% if current_user %>
      <%= link_to 'Logout', session_path('current'), method: 'delete' %>
      <h5> <%= User.find(session[:user_id]).email %></h5>
      <%= link_to 'New Entry', new_document_path %>
      <a href = "/documents"> All Documents </a>
    <%else %>
      <%= link_to "Sign Up", new_user_path %>
      <br/>
      <%= link_to "Log In", new_session_path %>
    <% end%>


    <!--for verification of the users -->
    <% if current_user %>
    <% if User.find(session[:user_id]).superadmin? %>
      <p><a href = "/users"> User Verification </a></p>
    <% end %>
    <%end %>


    <!-- This part is for flash messages -->
    <% flash.each do |key, value| -%>
      
        <div id="flash" class = "alert alert-warning">

        <div id="flash_<%= key %>"><%=h value %></div>

      </div>
    <% end %>


    <%= yield %>
  </body>
</html>

app/views/users/index.html.erb
<h2>All Unverified Users</h2>
<p> Verifying a user will allow them to create new entries for documents, check on upcoming deadlines and delete entries  </p>
<hr/>
<div> 
	<% @users.each_with_index do |user, index| %>
		<% index +=1 %>
		<p><%= index %> ) <%= user.title %>
				<strong><%= user.last_name %> </strong>
				<%= user.first_name %>
		</p>

		<p> <%= user.email %></p>

		<%= form_tag("/users/#{user.id}", method: :patch) do %>
	    	<input type="submit" value="Verify User" />
		<% end %> 

		<br/>

		<% end %>

</div>

app/views/users/new.html.erb
<h1> Sign up </h1>

<%= form_for @user do |f| %>
	<% if @user.errors.any? %>
		<div class= "errors">
			<h3>Form is invalid</h3>
			<ul>
				<% @user.errors.full_messages.each do |m| %>
					<li> <%= m %> </li>
				<% end %>
			</ul>
		</div>
	<% end %>

	<div class="field">
		<%= f.label :"First Name" %><br/>
		<%= f.text_field :first_name %>
	</div>

	<div class="field">
		<%= f.label :"Last Name" %><br/>
		<%= f.text_field :last_name %>
	</div>

	<div class="field">
		<%= f.label :Title %><br/>
		<%= f.text_field :title %>
	</div>

	<div class="field">
		<%= f.label :Email %><br/>
		<%= f.text_field :email %>
	</div>

	<div class="field">
		<%= f.label :password %><br/>
		<%= f.password_field :password %>
	</div>

	<div class="field">
		<%= f.label :"confirm password" %><br/>
		<%= f.password_field :password_confirmation %>
	</div>

	<div class="submit">
		<%= f.submit "Sign Up" %></div>

<% end %>

app/views/welcome/index.html.erb
<br/><br/><br/>
<%= link_to "Random Payment Setup", braintree_new_path %>